### ISSUE TITLE
feature request: Support STS (pod-identity webhook)

### ISSUE THREAD

**Issue by paulczar** [rh-mobb/ecr-secret-operator#1]
The Operator should be able to use a STS token to create user/key required for the pullsecret rather than the pull secret itself.

ROSA allows for injecting STS credentials using the pod-identity webhook which lets you provide a trustPolicy to tell the IAM Role to trust a specific annotated K8s service-account, which then injects a STS token into a pod without needing user key/secret.

An example of creating IAM role / policy / trust-policy in order to use STS inside a pod - https://mobb.ninja/docs/rosa/aws-secrets-manager-csi/

**Comment by datianshi** [comment]
This is resolved by 0.3
