### ISSUE TITLE
feature request: add secret to multiple namespaces

### ISSUE THREAD

**Issue by paulczar** [rh-mobb/ecr-secret-operator#2]
The operator should be able to automatically add the pull secret to one or more namespaces. Some suggestions:

1) Operator only manages the namespace its in ... therefore requires minimal RBAC
2) Operator creates pull secrets for all namespaces (except for kube-system, openshift-*, etc), requires heightened RBAC
3) Operator watches for namespaces with a certain annotation which tells it to manage an ECR pull secret (for a specific repo ?)

**Comment by datianshi** [comment]
This is solved by 0.3
